# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: format
    name: Format Rust code
    language: system
    entry: just fmt
    types_or: [rust, cargo, cargo-lock]
    stages: [pre-commit, pre-merge-commit, pre-push, manual]
    pass_filenames: false
    require_serial: true
  - id: format-py
    name: Format Python code
    language: system
    entry: just fmt-py
    types_or: [python]
    stages: [pre-commit, pre-merge-commit, pre-push, manual]
    pass_filenames: false
    require_serial: true
