[mypy]
# Exclude test files
exclude = (?x)(
    tests/
    | test_.*\.py$
    | _test\.py$
  )
plugins = pandera.mypy

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-sklearn.*]
ignore_missing_imports = True
