name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dipper-service-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

    - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

    - uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
      id: meta
      with:
        images: ghcr.io/edgeandnode/dipper-service
        tags: |
          type=ref,event=tag
          type=sha

    - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        file: Dockerfile
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
        pull: true
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/dipper-service:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner}}/dipper-service:buildcache,mode=max

  dipper-cli-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

    - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

    - uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
      id: meta
      with:
        images: ghcr.io/edgeandnode/dipper-cli
        tags: |
          type=ref,event=tag
          type=sha

    - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
      with:
        file: Dockerfile.dipper-cli
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
        pull: true
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/dipper-cli:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner}}/dipper-cli:buildcache,mode=max

  dipper-cli:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@02be93da58aa71fb456aa9c43b301149248829d8 # v1
        with:
          target: ${{ matrix.target }}
          rustflags: ''
          cache: false

      - name: Cache Rust build files
        uses: leafwing-studios/cargo-cache@43ec9a5bad6e7f174e7fc65dcf533de75ff65881 # v2
        with:
          sweep-cache: true

      - name: Build executable (release)
        run: cargo build --package dipper-cli --bin dipper-cli --target=${{ matrix.target }} --release

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: dipper-cli-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/dipper-cli
          if-no-files-found: error
