name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dipper-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Prepare build env
        run: sudo apt-get install -y lld protobuf-compiler

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1
        with:
          target: x86_64-unknown-linux-gnu
          rustflags: ''
          cache: false

      - name: Cache Rust build files
        uses: leafwing-studios/cargo-cache@a0709d80dd96c8734ac8f186c1f238c8f528d198 # v2
        with:
          sweep-cache: true

      - name: Build executable (release)
        run: cargo build --bin dipper-cli --target=x86_64-unknown-linux-gnu --release

      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: dipper-cli-x86_64-unknown-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/dipper-cli
          if-no-files-found: error

  dipper-service:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3

    - uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5
      id: meta
      with:
        images: ghcr.io/edgeandnode/dipper-service
        tags: |
          type=ref,event=tag
          type=sha

    - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc # v6
      with:
        file: Dockerfile
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: ${{ github.event_name != 'pull_request' }}
        pull: true
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/dipper-service:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner}}/dipper-service:buildcache,mode=max
