name: ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ 'main' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: true
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: '-C link-arg=-fuse-ld=lld'

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Prepare build env
        run: sudo apt-get install -y lld

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1
        with:
          components: clippy
          cache: false

      - name: Cache rust build files
        uses: leafwing-studios/cargo-cache@5d5d363fa3b9886d45c4705228c5c73ccea17636 # v2
        with:
          sweep-cache: true

      ## Check
      - run: cargo clippy -- -D warnings --force-warn deprecated --force-warn dead-code

      ## Test
      # Install uv (to manage Python versions and dependencies)
      - name: Setup uv
        uses: astral-sh/setup-uv@3b9817b1bf26186f03ab8277bab9b827ea5cc254 # v3
        with:
          enable-cache: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python and install dependencies
        id: python
        run: |
          # Install Python dependencies
          uv sync --frozen --no-dev --no-install-project
          
          # Set PYTHON_LIB_DIR output param to the directory containing the libpython shared library
          echo "PYTHON_LIB_DIR=$(dirname `uv tool run find_libpython`)" >> $GITHUB_OUTPUT

      # Install sops (needed for decrypting tests .env file)
      - name: Setup sops
        uses: nhedger/setup-sops@358bac533e4e92f9ce9f9da563d6265929c88cda # v2

      # Install age (needed for decrypting tests .env file)
      - name: Setup age
        uses: alessiodionisi/setup-age-action@82b9aea163ade7fe23441552a514cf666b214077 # v1.3.0

      - name: Unit tests
        uses: LNSD/sops-exec-action@6da1fbca63459d9796097496d5f5e6233555b31a # v1
        env:
          SOPS_AGE_KEY: ${{ secrets.IT_TESTS_AGE_KEY }}
          PYTHON_LIB_DIR: ${{ steps.python.outputs.PYTHON_LIB_DIR }}
        with:
          env_file: .env
          run: uv run --frozen cargo test 'tests::' -- --skip 'tests::it_'

      - name: Integration tests (in-tree)
        uses: LNSD/sops-exec-action@6da1fbca63459d9796097496d5f5e6233555b31a # v1
        env:
          SOPS_AGE_KEY: ${{ secrets.IT_TESTS_AGE_KEY }}
          PYTHON_LIB_DIR: ${{ steps.python.outputs.PYTHON_LIB_DIR }}
        with:
          env_file: .env
          run: uv run --frozen cargo test 'tests::it_'

      - name: Integration tests (public api)
        uses: LNSD/sops-exec-action@6da1fbca63459d9796097496d5f5e6233555b31a # v1
        env:
          SOPS_AGE_KEY: ${{ secrets.IT_TESTS_AGE_KEY }}
          PYTHON_LIB_DIR: ${{ steps.python.outputs.PYTHON_LIB_DIR }}
        with:
          env_file: .env
          run: uv run --frozen cargo test --test '*'

  format-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # v1
        with:
          toolchain: nightly
          components: rustfmt
          cache: false

      - run: cargo +nightly fmt --all -- --check

  test-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

    - uses: astral-sh/setup-uv@3b9817b1bf26186f03ab8277bab9b827ea5cc254 # v3
      with:
        enable-cache: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python and install dependencies
      run: uv sync --frozen --dev

    - name: Check Python code (ruff)
      run: uv run --frozen ruff check assets

    - name: Run mypy static type checker
      run: uv run --frozen mypy assets

    - name: Run Python tests
      run: uv run --frozen pytest assets

  format-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

    - uses: astral-sh/setup-uv@3b9817b1bf26186f03ab8277bab9b827ea5cc254 # v3
      with:
        enable-cache: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check Python code formatting (ruff)
      run: uv run --frozen ruff format --check assets
