name: ci
on:
  pull_request:
  push:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  RUSTFLAGS: '-C link-arg=-fuse-ld=lld'

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@8763a8b3c2f500b6c17550b7aed48ff4bc86aee6 # v2

      - name: Prepare build env
        run: sudo apt-get install -y lld

      - run: cargo clippy -- -D warnings --force-warn deprecated --force-warn dead-code

      ## Test
      - name: Run tests
        run: cargo test

  format-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly
          components: rustfmt

      - run: cargo +nightly fmt --all -- --check

  test-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Check Python code (ruff)
      uses: chartboost/ruff-action@491342200cdd1cf4d5132a30ddc546b3b5bc531b # v1
      with:
        args: 'check'
        src: 'assets'

  format-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    - name: Check Python code formatting (ruff)
      uses: chartboost/ruff-action@491342200cdd1cf4d5132a30ddc546b3b5bc531b # v1
      with:
        args: 'format --check'
        src: 'assets'
